# Generated by Django 5.1.4 on 2026-09-14 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_initial'),
        ('leads', '0004_lead_business_duration_lead_current_profession_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_automation_enabled',
            field=models.BooleanField(default=True, help_text='Disables automated qualification when human salesperson takes over'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='pending_investment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Transient storage during investment confirmation step', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('QUALIFYING', 'Qualifying'), ('WAITING_INVESTMENT', 'Waiting Investment'), ('CONFIRMING_INVESTMENT', 'Confirming Investment'), ('WAITING_PROFESSION', 'Waiting Profession'), ('WAITING_BUSINESS_DURATION', 'Waiting Business Duration'), ('WAITING_PREVIOUS_EXPERIENCE', 'Waiting Previous Experience'), ('WAITING_LOCATION', 'Waiting Location'), ('WAITING_OPENING_TIMELINE', 'Waiting Opening Timeline'), ('QUALIFIED', 'Qualified'), ('DISQUALIFIED', 'Disqualified'), ('HUMAN_HANDOFF', 'Human Handoff')], db_index=True, default='NEW', max_length=40),
        ),
        migrations.CreateModel(
            name='InstagramContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_account_id', models.CharField(db_index=True, help_text='ID of connected Instagram Professional account', max_length=255)),
                ('instagram_user_id', models.CharField(db_index=True, help_text='Stable external Meta IG User ID', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_contacts', to='users.brand')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_contacts', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('brand', 'instagram_account_id', 'instagram_user_id')},
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='instagram_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='conversations.instagramcontact'),
        ),
    ]
