# Generated by Django 5.1.4 on 2026-09-20 15:53

from django.db import migrations, models


def convert_qualified_to_complete(apps, schema_editor):
    Conversation = apps.get_model('conversations', 'Conversation')
    Conversation.objects.filter(state='QUALIFIED').update(state='QUALIFICATION_COMPLETE')

def reverse_convert_complete_to_qualified(apps, schema_editor):
    Conversation = apps.get_model('conversations', 'Conversation')
    Conversation.objects.filter(state='QUALIFICATION_COMPLETE').update(state='QUALIFIED')

class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_is_automation_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('QUALIFYING', 'Qualifying'), ('WAITING_INVESTMENT', 'Waiting Investment'), ('CONFIRMING_INVESTMENT', 'Confirming Investment'), ('WAITING_PROFESSION', 'Waiting Profession'), ('WAITING_BUSINESS_DURATION', 'Waiting Business Duration'), ('WAITING_PREVIOUS_EXPERIENCE', 'Waiting Previous Experience'), ('WAITING_LOCATION', 'Waiting Location'), ('WAITING_OPENING_TIMELINE', 'Waiting Opening Timeline'), ('QUALIFICATION_COMPLETE', 'Qualification Complete'), ('DISQUALIFIED', 'Disqualified'), ('HUMAN_HANDOFF', 'Human Handoff')], db_index=True, default='NEW', max_length=40),
        ),
        migrations.RunPython(
            convert_qualified_to_complete,
            reverse_code=reverse_convert_complete_to_qualified
        ),
    ]
