# Generated by Django 5.1.4 on 2026-09-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('QUALIFICATION_CHANGED', 'Qualification Changed'), ('STATUS_CHANGED', 'Sales Status Changed'), ('NOTE_ADDED', 'Note Added'), ('FOLLOW_UP_SCHEDULED', 'Follow Up Scheduled'), ('FOLLOW_UP_COMPLETED', 'Follow Up Completed'), ('LEAD_CONVERTED', 'Lead Converted'), ('LEAD_LOST', 'Lead Lost')], max_length=40)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('preferred_location', models.CharField(blank=True, default='', max_length=100)),
                ('investment_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('property_available', models.BooleanField(default=False)),
                ('business_experience', models.BooleanField(default=False)),
                ('expected_start', models.CharField(blank=True, default='', max_length=100)),
                ('lead_source', models.CharField(choices=[('MANUAL', 'Manual'), ('TEST', 'Test'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Website'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('GOOGLE_ADS', 'Google Ads'), ('OTHER', 'Other')], db_index=True, default='MANUAL', max_length=30)),
                ('qualification_score', models.IntegerField(default=0)),
                ('qualification_status', models.CharField(choices=[('QUALIFIED', 'Qualified'), ('REVIEW', 'Review'), ('NOT_QUALIFIED', 'Not Qualified')], db_index=True, default='REVIEW', max_length=30)),
                ('qualification_reason', models.TextField(blank=True, default='')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('follow_up_type', models.CharField(blank=True, choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('MEETING', 'Meeting'), ('EMAIL', 'Email'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('follow_up_note', models.TextField(blank=True, default='')),
                ('sales_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('FOLLOW_UP', 'Follow Up'), ('MEETING', 'Meeting'), ('NEGOTIATION', 'Negotiation'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=30)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Lead Sequence Counter',
            },
        ),
    ]
