# Generated by Django 5.1.4 on 2026-09-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_investment_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='business_duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_profession',
            field=models.CharField(blank=True, choices=[('BUSINESS', 'Business'), ('SALARIED', 'Salaried'), ('SELF_EMPLOYED', 'Self Employed'), ('STUDENT', 'Student'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_temperature',
            field=models.CharField(blank=True, choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold'), ('LONG_TERM', 'Long Term'), ('DISQUALIFIED', 'Disqualified')], db_index=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='opening_timeline',
            field=models.CharField(blank=True, choices=[('WITHIN_2_MONTHS', 'Within 2 months'), ('WITHIN_6_MONTHS', 'Within 6 months'), ('WITHIN_1_YEAR', 'Within 1 year'), ('MORE_THAN_1_YEAR', 'More than 1 year'), ('NOT_DECIDED', 'Not decided yet')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='previous_business_experience',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('QUALIFICATION_CHANGED', 'Qualification Changed'), ('LEAD_TEMPERATURE_CHANGED', 'Lead Temperature Changed'), ('LEAD_DISQUALIFIED', 'Lead Disqualified'), ('QUALIFICATION_COMPLETED', 'Qualification Completed'), ('STATUS_CHANGED', 'Sales Status Changed'), ('NOTE_ADDED', 'Note Added'), ('FOLLOW_UP_SCHEDULED', 'Follow Up Scheduled'), ('FOLLOW_UP_COMPLETED', 'Follow Up Completed'), ('LEAD_CONVERTED', 'Lead Converted'), ('LEAD_LOST', 'Lead Lost'), ('INSTAGRAM_MESSAGE_RECEIVED', 'Instagram Message Received'), ('INSTAGRAM_MESSAGE_SENT', 'Instagram Message Sent')], max_length=40),
        ),
    ]
