# Generated by Django 5.1.4 on 2026-09-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('gte', 'Greater than or equal (>=)'), ('lte', 'Less than or equal (<=)'), ('eq', 'Equals (=)'), ('contains', 'Contains'), ('is_true', 'Is True'), ('is_false', 'Is False')], max_length=20)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
